GibbsConsulting/django-plotly-dash

README.md, demo/demo/asgi.py, demo/demo/consumers.py, demo/demo/plotly_apps.py, demo/demo/settings.py, demo/demo/static/demo/demo.css, demo/demo/templates/base.html, demo/demo/templates/demo_four.html, demo/demo/templates/demo_one.html, demo/demo/templates/demo_three.html, demo/demo/templates/demo_two.html, demo/demo/templates/index.html, demo/demo/templates/second_page.html, demo/demo/urls.py, dev_requirements.txt, django_plotly_dash/__init__.py, django_plotly_dash/dash_wrapper.py, django_plotly_dash/migrations/0002_add_examples.py, docs/introduction.rst, requirements.txt, setup.py
Collection of mainly documentation and demo enhancements.
Enforce a minimum version of v2.0 for Django - issue #9 thanks to @hannylicious for the report.
=> Prerelease 0.4.3

django_plotly_dash/__init__.py
=> Prerelease version 0.5.2

check_code, check_code_demo, check_code_demo_test, demo/demo/plotly_apps.py, demo/demo/templates/demo_four.html, demo/demo/templates/demo_one.html, demo/demo/templates/demo_three.html, demo/demo/templates/demo_two.html, demo/demo/tests/test_dpd_demo.py, django_plotly_dash/dash_wrapper.py, django_plotly_dash/models.py, django_plotly_dash/templatetags/plotly_dash.py, django_plotly_dash/tests.py, django_plotly_dash/urls.py, django_plotly_dash/views.py, docs/template_tags.rst
Specify initial arguments for a dash app when invoking the app in a template.
The presence of initial state is indicated through new Django routes and the state pushed through the default cache.
=> Initial arguments

django_plotly_dash/__init__.py
=> Increment version number to 0.9.0

dev_requirements.txt, dev_requirements.yaml, django_plotly_dash/dash_wrapper.py, docs/dash_components.rst, docs/development.rst, docs/extended_callbacks.rst, docs/faq.rst, docs/license.rst, docs/models_and_state.rst, docs/template_tags.rst
=> Documentation and other fixes

demo/demo/settings.py, django_plotly_dash/access.py, django_plotly_dash/urls.py, docs/configuration.rst, docs/faq.rst
A first attempt at a framework for #56
=> Fine-grained access control

demo/demo/templates/demo_four.html, django_plotly_dash/__init__.py, django_plotly_dash/templatetags/plotly_dash.py
Added site lookup for curl url in demo.
Bump patch release version.
=> Added site lookup for curl url in demo

.travis.yml, dev_requirements.txt, dev_requirements.yaml
Extended travis configuration to push coverage results through coveralls
=> Adding Coveralls to Travis CI build

docs/simple_use.rst
=> Add note to emphasize necessary imports

django_plotly_dash/dash_wrapper.py
Change use of json response from flask
=> Change handling of json response due to underlying library change

demo/demo/bootstrap_app.py, demo/demo/plotly_apps.py, demo/demo/settings.py, dev_requirements.txt, django_plotly_dash/dash_wrapper.py, django_plotly_dash/middleware.py, django_plotly_dash/templatetags/plotly_dash.py, django_plotly_dash/util.py, django_plotly_dash/version.py, django_plotly_dash/views.py, docs/configuration.rst, docs/installation.rst
Some tweaks to the documentation.
Add renderer to direct rendering for #142 
Improve documentation to help with #121 and also #140
=> Improve docs and other fixes

django_plotly_dash/util.py, docs/configuration.rst
=> Change serve_locally default to always be false

django_plotly_dash/dash_wrapper.py
This should close issue #149. This is a purely additive change.
Adding support for client-side callbacks is just a matter of registering a javascript function name. The client-side callback may be registered by calling the `clientside_callback` function on a `DjangoDash` object in the same exact way as it would have been done with a plain Dash app (see: https://community.plot.ly/t/dash-0-41-0-released/22131).
=> Add support for dash client-side callbacks

demo/demo/scaffold.py, demo/demo/settings.py, demo/demo/tests/test_demo_app.py, django_plotly_dash/dash_wrapper.py, django_plotly_dash/tests.py, django_plotly_dash/util.py, django_plotly_dash/version.py
Hook for adding extra app lookup
=> Add an extra hook for locating and loading stateless apps

django_plotly_dash/dash_wrapper.py, django_plotly_dash/version.py
Fix a typo in the lookup hook code.
=> Fix typo and bump version

django_plotly_dash/version.py, setup.py
=> Add Framework :: Dash classifier

django_plotly_dash/dash_wrapper.py, django_plotly_dash/models.py, django_plotly_dash/templates/admin/django_plotly_dash/statelessapp/change_list.html, django_plotly_dash/tests.py, django_plotly_dash/urls.py, django_plotly_dash/views.py, docs/demo_notes.rst, docs/models_and_state.rst
Admin button to add ORM instances for otherwise unregistered StatelessApp instances
=> Add admin functionality to register new apps

demo/demo/templates/index.html, django_plotly_dash/version.py
Switch formatting from list to table.
Addresses #195
=> Improve demo list formatting

demo/demo/plotly_apps.py, demo/demo/templates/demo_ten.html, demo/demo/tests/test_dpd_demo.py, django_plotly_dash/views.py
=> Add handling of PreventUpdate exceptions

django_plotly_dash/version.py
=> Bumped version

django_plotly_dash/views.py
request object so that callback can use request.META
=> Add request object to call back

CONTRIBUTIONS.md
=> Update contributor list

README.md, django_plotly_dash/version.py, docs/bootstrap.rst, docs/index.rst, docs/installation.rst
Documentation for setting up use of bootstrap.
Addresses #230
=> Add checklist for bootstrap installation

django_plotly_dash/dash_wrapper.py
first attempt at supporting pattern matching (fix #264 and #277)
support for:
- initial_arguments
- dispatch by dpd
todo:
=> support pattern matching

demo/demo/urls.py, django_plotly_dash/routing.py
=> replace url() by path/re_path() in demo app

demo/demo/plotly_apps.py, django_plotly_dash/dash_wrapper.py, django_plotly_dash/migrations/0002_add_examples.py, django_plotly_dash/models.py, django_plotly_dash/tests.py, django_plotly_dash/tests_dash_contract.json, django_plotly_dash/tests_dash_contract.py
components with IDs as dict (pattern) are now properly managed in state
bug #292 is fixed
=> handling State for pattern + fix #292

django_plotly_dash/version.py, requirements.txt
=> Restrict dash 1 21 0

requirements.txt
dash-bootstrap-components v1 requires dash 2
=> set dash-bootstrap-components version

.gitignore, django_plotly_dash/templates/django_plotly_dash/plotly_app.html, django_plotly_dash/templates/django_plotly_dash/plotly_app_bootstrap.html, django_plotly_dash/templatetags/plotly_dash.py
Addresses #411 
Provides a single code-generated list of sandbox exceptions within template tags.
=> Sandbox permissions

demo/demo/bootstrap_app.py, make_env, requirements.txt
Should ease the pain reported in #413
=> Relax historical constraints and move to Python 3.10 as base version

django_plotly_dash/version.py, setup.py
Update dependencies in setup file.
Addresses #424
=> Fix package dependencies

django_plotly_dash/_patches.py
=> Fix reference to plotly json config object

django_plotly_dash/_patches.py, django_plotly_dash/version.py
=> Fix use of orjson

CONTRIBUTIONS.md, django_plotly_dash/version.py
Update package version to 2.1.4
=> Update version to 2.1.4

demo/demo/templates/demo_four.html
Change curl instruction documentation to cover redirection case.
Possible alternative to #437
=> Add redirection to curl instruction

demo/demo/settings.py, django_plotly_dash/finders.py, django_plotly_dash/version.py, requirements.txt, setup.py
=> Allow use of current Dash versions by updating asset loading

django_plotly_dash/models.py, django_plotly_dash/version.py
=> Fix import error

django_plotly_dash/finders.py
The `all` flag has been deprecated and the `find_all` flag is being used in Django 5.2 for the various static file finders.
See: https://github.com/typeddjango/django-stubs/issues/2495 as an example.
This fix makes the Dash***Finder classes work in both circumstances without breaking.
=> fix: Allow for both the new find_all flag and the all flag in Finders.
