django_plotly_dash/util.py

Handle missing PLOTLY_DASH settings gracefully

---

demo/demo/plotly_apps.py
django_plotly_dash/dash_wrapper.py
django_plotly_dash/util.py

First cut of a fix for #21 - adds a dummy register_blueprint function.
Dash apps that use this function will not work correctly.

Dash 22 upgrade

---

demo/demo/templates/demo_one.html
django_plotly_dash/dash_wrapper.py
django_plotly_dash/templates/django_plotly_dash/plotly_app.html
django_plotly_dash/templatetags/plotly_dash.py
docs/template_tags.rst

Added the generation and optional use of class name and unique identifiers for app templates.
This addresses #20 
One template tag - plotly_class - is provided to generate a list of names, suitable for use as css names or identifiers, given a django-plotly-dash app and optional prefix and postfix strings.
A second tag - plotly_app_identifier - returns the internal (slug-friendly) name for the app, annotated with an optional postfix string.
The user has to decide how to wield these tools - it is hard to see how the choice between class name and identifier can be automated, and in the case of identifiers how to ensure uniqueness when multiple apps are present.

Parent div and frame identifiers

---

demo/demo/plotly_apps.py
demo/demo/settings.py
demo/demo/templates/base.html
demo/demo/templates/demo_four.html
demo/demo/urls.py
django_plotly_dash/routing.py
django_plotly_dash/urls.py
django_plotly_dash/util.py
django_plotly_dash/views.py
docs/configuration.rst
docs/dash_components.rst
docs/installation.rst
docs/introduction.rst
docs/template_tags.rst
docs/updating.rst

Added documentation for live app updating using websockets or similar.
Added http endpoint to allow insertion (eg using curl) of values into the demo apps

Documentation for live updating

---

django_plotly_dash/__init__.py
frozen_dev.txt

This (pre) release contains pull requests 17 (documentation typos), 27 (licensing preamble and contributor list),
28 (css classes and identifiers), and 29 (documentation on live updating).

Prerelease 0.6.0

---

requirements.txt
setup.py

Fix minimum version of Flask (1.0.2) and Django (2) in both requirements and setup.py files.
Addresses #31 which is assumed to be due to use of older versions of Flask.

FIx minimum Flask and Django versions

---

demo/demo/dash_apps.py
demo/demo/plotly_apps.py
demo/demo/settings.py
demo/demo/templates/base.html
demo/demo/templates/demo_five.html
demo/demo/templates/demo_four.html
demo/demo/templates/demo_six.html
demo/demo/templates/index.html
demo/demo/tests/test_dpd_demo.py
demo/demo/urls.py
demo/demo/views.py
django_plotly_dash/dash_wrapper.py
django_plotly_dash/middleware.py
django_plotly_dash/templates/django_plotly_dash/plotly_direct.html
django_plotly_dash/templatetags/plotly_dash.py
django_plotly_dash/tests.py
django_plotly_dash/util.py
docs/configuration.rst
docs/template_tags.rst

A new template tag - plotly_direct - is added to enable direct use of dash rather than embedded in an iframe.
This addresses #19 
In addition, a cache timeout parameter has been added to address #33

Html formation to enable dash app without iframe

---

django_plotly_dash/access.py
docs/access_control.rst
docs/configuration.rst
docs/faq.rst
docs/index.rst

Documentation for the ``view_decorator`` configuration argument,

Added documentation for per-view access control

---

django_plotly_dash/dash_wrapper.py
frozen_dev.txt

that was introduced due to this refactoring: https://github.com/plotly/dash/issues/531

Resolving bug with dash 0.36

---

django_plotly_dash/finders.py

Handle the case of a missing settings variable containing the list of dash components to include when searching for static files.

Make static finders handle case of missing settings gracefully

---

.travis.yml
dev_requirements.txt
requirements.txt

This may require a
```
before_install:
apt-get install sqlite3
```
section in `.travis.yml` if sqlite3 is not pre-installed in the base xenial image. I leave it out for now so. that the Travis tests can run on me opening this PR.

Upgrade ci build

---

django_plotly_dash/version.py

New prerelease 0.9.10
This version should work with newer versions of underlying packages by handling alternative formats for json responses.

Increase version number to 0.9.10

---

README.md
django_plotly_dash/util.py
docs/configuration.rst
docs/demo_notes.rst
docs/development.rst
docs/faq.rst
docs/introduction.rst

Add online demo info to documentation and readme

---

django_plotly_dash/views.py

Starting from dash version 1.5.0, dash created two methods:
- build_fingerprint
- check_fingerprint
those methods change the way the resource name is built and sent to component_suites view. I'm using check_fingerprint to get the correct name of the resource before the redirect.

add check_fingerprint to component_suits view

---

CONTRIBUTIONS.md
django_plotly_dash/views.py

Dash now has a fingerprint module, and dpd has been updated to use it. See #187 
This PR wraps the import of the module so that older dash versions without the module can still be used.

Handle case of missing dash.fingerprint module

---

demo/demo/plotly_apps.py
demo/demo/scaffold.py
demo/demo/templates/demo_ten.html
demo/demo/templates/index.html
demo/demo/urls.py
django_plotly_dash/dash_wrapper.py
django_plotly_dash/migrations/0002_add_examples.py
django_plotly_dash/tests.py

Permit multiple return values from callbacks.
Add an example demonstrating use of multiple return values.
Fix up storage of callback return values in ORM.

Add handling of multiple return values from callbacks

---

demo/demo/templates/demo_seven.html
django_plotly_dash/models.py
django_plotly_dash/templates/django_plotly_dash/plotly_app.html
django_plotly_dash/templates/django_plotly_dash/plotly_app_bootstrap.html
django_plotly_dash/templatetags/plotly_dash.py
docs/template_tags.rst

Add a new template tag `plotly_app_bootstrap` that uses Bootstrap4 to make its `iframe` be responsive.
Addresses #35, and also implies that #84 has been already resolved.

Responsive template using Bootstrap

---

demo/demo/templates/base.html
django_plotly_dash/middleware.py
django_plotly_dash/templates/django_plotly_dash/plotly_messaging.html
django_plotly_dash/version.py

Stop dpd middleware from raising exceptions on files with streaming content
Bump version to 1.1.3
Change load tag from staticfiles to static

Allow media files to propagate through dpd middleware

---

demo/demo/bootstrap_app.py
demo/demo/settings.py
django_plotly_dash/version.py

Extend the bootstrap example to include checkboxes that are sensitive to the version of bootstrap used.
Version 4.3.1 of bootstrap (or higher) is needed for this to render correctly.

Extend bootstrap example to show switch and checkbox variants

---

demo/demo/settings.py
requirements.txt
setup.py

Remove constraint requiring use of Django 3.0
Update the documentation for X_FRAME_OPTIONS to permit use of iframes

Allow use of Django 3.0

---

django_plotly_dash/dash_wrapper.py

There was a missing 's' in line 629, wich leads to an error if you try to use dash States
"for c in state:" --> "for c in state:"

Correct dash State in dash_wrapper.py

---

CONTRIBUTIONS.md
django_plotly_dash/version.py
requirements.txt

Partly addresses #291 by suppressing the use of later channels versions

Update requirements to avoid use of later channels

---

demo/demo/dash_apps.py
dev_requirements.txt
django_plotly_dash/dash_wrapper.py
django_plotly_dash/tests.py

- simplify single_case vs multiple_case handling
- refactor calls to self.callback_map[target_id]
- adapt tests
- (misc) add missing dev dep on dash-bootstrap-components

fix #305: bug when output is list of one Output

---

check_code_dpd
demo/demo/dash_apps.py
demo/demo/plotly_apps.py
demo/demo/scaffold.py
dev_requirements.txt
django_plotly_dash/dash_wrapper.py
django_plotly_dash/tests.py
django_plotly_dash/views.py
docs/demo_notes.rst
docs/extended_callbacks.rst

allow a more flexible use of expanded_callback:
- no obligation to adapt the signature of a callback (by adding a **kwargs) when going from app.callback to app.expanded_callback 
- allow to specify the name of the specific extra parameters needed by the function (no need for **kwargs) to improve readability like in
```python
@app.expanded_callback(...)
def my_callback(..., **kwargs): ...
@app.expanded_callback(...)
def my_callback(...): ...
@app.expanded_callback(...)
def my_callback(..., user, callback_context): ...
@app.expanded_callback(...)
def my_callback(..., user, callback_context, **kwargs): ...
```

Flexible expanded callback

---

CHANGELOG.md
django_plotly_dash/dash_wrapper.py
django_plotly_dash/version.py

Insert stub function for backwards compatibility

---

CHANGELOG.md
django_plotly_dash/dash_wrapper.py
django_plotly_dash/tests.py

no need to group Outputs, Inputs and States into list.
```
@ddash.callback(
Output("one", "foo"),
Output("two", "foo"),
Input("one", "baz"),
Input("two", "baz"),
Input("three", "baz"),
State("one", "bil"),
)
```
is now equivalent to
```
@ddash.callback(
[Output("one", "foo"),
Output("two", "foo")],
[Input("one", "baz"),
Input("two", "baz"),
Input("three", "baz")],
[State("one", "bil")]
)
```

Align dpd callback signature to Dash one

---

demo/demo/tests/test_dpd_demo.py
django_plotly_dash/util.py

- converting initial_arguments given as json string into a dict in `store_initial_arguments`
- add in the test of the template tag a call to the _dash-layout to ensure the initial_arguments are parsed properly

fix #328 (initial_arguments broken)

---

django_plotly_dash/dash_wrapper.py
django_plotly_dash/tests.py
django_plotly_dash/tests_dash_contract.json
django_plotly_dash/tests_dash_contract.py

- update test to cover updating state via output
- add lazy parsing of json response
In case we have a DashApp with state to save, the json output of the response is always parsed (json str -> dict) even though sometimes it is not used as the output are not in the da.current_state(). This PR "lazifies" the access to the response keys/values by delaying the `root_value = json.loads(res)` till the first `root_value.get(output_id,{})`.
When returning large figures (that are not saved in the state usually...) in the output, we save the parsing of the json str.

parse JSON response to update DA state only if needed

---

docs/installation.rst

There is still confusion around how to register a Plotly app with Dash. These instructions belong inside the Installation document since that is the first thing people will likely read when using Dash.
Related issue #102

Clarify the importance of registering plotly app

---

docs/configuration.rst

This fixes a typo for the initial configuration from `"serve_locally': False,` to `"serve_locally": False,`

Fixes typo in Configuration.rst

---

django_plotly_dash/templates/django_plotly_dash/plotly_app.html
requirements.txt

In some demos (see #388) and other applications I'm working on the dash dashboard will never load (tested on an up to date Arch Linux and CentOS 8, using firefox and chrome). When that happens the developer console in the browser tells us the errors are related to the sandboxing. Adding `allow-scripts allow-same-origin` fixes this issue.
While I was doing this, with the default version of the requirements Django 4.0.3 will be installed but at the moment it's not compatible so I'm adding a commit to use the 3.2.12 version instead. This is what one gets when running with Django 4.0.3 after `prepare_demo:`
```
Exception in thread django-main-thread:
Traceback (most recent call last):
File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
self.run()
File …
```

Fix getting stuck at loading

---

demo/demo/plotly_apps.py
django_plotly_dash/__init__.py
django_plotly_dash/_patches.py
django_plotly_dash/dash_wrapper.py
django_plotly_dash/util.py

Monkey-patch the dash json conversion to add in lazy evaluation of text for Django.
Addresses #404

Extend to-json conversion to include lazy functions from Django

---

dev_requirements.txt
django_plotly_dash/dash_wrapper.py
django_plotly_dash/version.py
requirements.txt
setup.py

Make compatible with latest Flask and Dash releases

---

README.md

Updated Installation part of readme - put an emphasis on adding url namespace to the app urls.
This is due to the fact that [this issue](https://github.com/GibbsConsulting/django-plotly-dash/issues/117) seems to be pretty common throughout first-time users.

Update readme - namespace in urls

---

django_plotly_dash/version.py
requirements.txt
setup.py

Short term fix for #460 by limiting the Dash version to less than 2.10

Temporarily restrict Dash version as per #460 #461

---

django_plotly_dash/views.py

Requests with an empty body to the endpoint `_dash-update-component` are triggering an *500 Internal Server error* response. This issue has been observed in operational practice, web crawlers seem to pick up this endpoint and send a request with an empty body. Consequently, the cloud environment reports *500 Internal Server* errors.
This can be reproduced with the *Demo Four* app in this repository. Just send this request:
```
GET http://127.0.0.1:8000/django_plotly_dash/app/LiveInput/_dash-update-component
Accept: application/json
```
We get:
```
GET http://127.0.0.1:8000/django_plotly_dash/app/LiveInput/_dash-update-component
HTTP/1.1 500 Internal Server Error
```
The endpoint should respond with a *400 Bad Request* error.
The error occurs because the JSON deserialization of the empty …

Avoid 500 Internal Server Error if empty body is posted to _dash-update_component

---

demo/demo/asgi.py
demo/demo/settings.py
django_plotly_dash/routing.py
django_plotly_dash/version.py
prepare_demo
requirements.txt
setup.py

Enable use of channels and Django versions > 4.0
Provides a working asgi file for this new combination, along with a working (albeit with daphne) runserver for debugging.

Enable use of channels and Django versions 4.0

---

django_plotly_dash/dash_wrapper.py
django_plotly_dash/version.py
setup.py

Handle change in how Dash generates meta tags in app html and extend range of permitted Dash versions.
Dash versions less than 3.0 are now enabled via the package setup.py file.
Advance version to 2.4.0

Handle change in Dash meta generation

---

django_plotly_dash/version.py
requirements.txt
setup.py

Restrict the version of Dash to less than 2.13
This should provide a temporary fix to #502

Restrict Dash version to less than 2.13

---

django_plotly_dash/version.py

Version 2.4.2. had an unfortunate build artifact. An updated version has been pushed to PyPI, necessitating a bump in package number.

Bump version to 2.4.3

---

docs/extended_callbacks.rst

The url markup wasn't complete. Missing the closing bracket.

Fix typo in extended callbacks docs

---

django_plotly_dash/dash_wrapper.py
django_plotly_dash/version.py
pylintrc
requirements.txt
setup.py

Changes to make the package work with Dash versions >= 3.0
These changes enable the package to work, but do not necessarily allow all new features in Dash 3.0 to work.

Update dpd to work with dash versions > 3
